services:
  db:
    image: postgres:15
    container_name: person-pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1324
      POSTGRES_DB: persons_db
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - 6792:5432
    volumes:
      - postgres_volume_data:/var/lib/postgresql/data/

volumes:
  postgres_volume_data: